### ISSUE TITLE
There are problems on windows

### ISSUE THREAD

**Issue by psiquis** [WarManX/Iphone-Reserver#2]
root@DESKTOP-XXX:/mnt/c/Users/XXX/OneDrive/OneDrive - XXX/Desktop/Iphone-Reserver# python3 iphone_reserver.py
Traceback (most recent call last):
  File "/mnt/c/Users/XXX/OneDrive/OneDrive - Telefonica/Desktop/Iphone-Reserver/iphone_reserver.py", line 14, in <module>
    from pync import Notifier
  File "/usr/local/lib/python3.10/dist-packages/pync/__init__.py", line 3, in <module>
    from .TerminalNotifier import Notifier, notify, remove_notifications, list_notifications
  File "/usr/local/lib/python3.10/dist-packages/pync/TerminalNotifier.py", line 137, in <module>
    Notifier = TerminalNotifier()
  File "/usr/local/lib/python3.10/dist-packages/pync/TerminalNotifier.py", line 37, in __init__
    raise Exception("pync is only supported on Mac OS X 10.8, or higher.")
Exception: pync is only supported on Mac OS X 10.8, or higher.

**Comment by WarManX** [comment]
You can remove the notifier by just commenting the import and comment it from everywhere in the source code and try to run it again because it's not important and not required for the main purpose

**Comment by WarManX** [comment]
These lines just comment them

14
210

**Comment by WarManX** [comment]
Please let me know if it's working with you or not

**Comment by psiquis** [comment]
Perfectly. Thanks

**Comment by WarManX** [comment]
You are welcome👋🏼😁
